[tool.poetry]
name = "kursovaya-3"
version = "0.1.0"
description = ""
authors = ["Segrey Agapov <stigrov@ya.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
